import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#005236',
        'surface-container-highest': '#2d3449',
        'surface-container': '#171f33',
        'on-tertiary': '#472a00',
        'on-secondary': '#003824',
        'on-tertiary-container': '#3e2400',
        'secondary': '#4edea3',
        'surface-variant': '#2d3449',
        'surface-container-high': '#222a3d',
        'tertiary-fixed-dim': '#ffb95f',
        'surface-tint': '#c0c1ff',
        'background': '#0b1326',
        'surface-container-low': '#131b2e',
        'on-secondary-container': '#00311f',
        'tertiary-container': '#ca8100',
        'on-error': '#690005',
        'inverse-surface': '#dae2fd',
        'on-primary-container': '#0d0096',
        'inverse-on-surface': '#283044',
        'error': '#ffb4ab',
        'primary-fixed-dim': '#c0c1ff',
        'surface-bright': '#31394d',
        'outline': '#908fa0',
        'inverse-primary': '#494bd6',
        'primary-container': '#8083ff',
        'on-surface': '#dae2fd',
        'on-secondary-fixed': '#002113',
        'error-container': '#93000a',
        'tertiary-fixed': '#ffddb8',
        'on-tertiary-fixed': '#2a1700',
        'surface': '#0b1326',
        'on-primary-fixed-variant': '#2f2ebe',
        'on-tertiary-fixed-variant': '#653e00',
        'secondary-fixed': '#6ffbbe',
        'on-primary-fixed': '#001090',
        'primary': '#c0c1ff',
        'on-primary': '#0d0096',
        'tertiary': '#ffb95f',
        'outline-variant': '#2d3449',
        'scrim': '#000000',
        'on-surface-variant': '#c0c1ff',
      },
      fontFamily: {
        'plus-jakarta': ['Plus Jakarta Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
export default config
